apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: go-app # Add this label
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          ports:
            - containerPort: 8081
